apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-to-vault-params
  namespace: secrets-to-vault
  labels:
    app: secrets-to-vault
data:
  SECRETS_LABEL_SELECTOR: label1=value1,label2=value2
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
  VAULT_SECRETS_PREFIX: k8s-secrets
  VAULT_ROLE: k8s-secrets
