apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "secrets-to-vault.secrets-to-vault.svc.cluster.local"
webhooks:
  - name: "secrets-to-vault.secrets-to-vault.svc.cluster.local"
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["secrets"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: "secrets-to-vault"
        name: "secrets-to-vault"
        path: /sync
        port: 3000
      # url: https://
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpRENDQW5DZ0F3SUJBZ0lVSjkrMW56UTVsMWM4SWxwRGF2WC9uUFlMZ3N3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hERUxNQWtHQTFVRUJoTUNRVVV4RGpBTUJnTlZCQWdUQlVSMVltRnBNUTR3REFZRFZRUUhFd1ZFZFdKaAphVEVMTUFrR0ExVUVDaE1DUVVFeEN6QUpCZ05WQkFzVEFrRkJNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1CNFhEVEl6TURNeE9EQTFNRFV3TUZvWERUSTRNRE14TmpBMU1EVXdNRm93WERFTE1Ba0dBMVVFQmhNQ1FVVXgKRGpBTUJnTlZCQWdUQlVSMVltRnBNUTR3REFZRFZRUUhFd1ZFZFdKaGFURUxNQWtHQTFVRUNoTUNRVUV4Q3pBSgpCZ05WQkFzVEFrRkJNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdk02dE9xYVlERkx3VldOb2tGZmhlUk9EUHZQWk4vNUMvejE0aVEyclNhWVMKL3Jzb1h3Q2xnYjJsL1dZeDBxRUxkUWpMS2NBb2xWVzhIMW5xTU45NGlLV0FyS1laYmdmeDE1RGREQ1lOcW9CVgpzeUVzSXJlZFF4Q09yV1RCOTVhVFUvbFJZY2FEVURycDIrM1FOb3BuenBOMXNaL0NldVpLTjI1UHIzSWx3Y2pSCkU5SitjN09wYURWbWhZeWZReGZqWitTQlYreUlJTXZRUGRSWmk0K2NVZUxVNjZzcFptUVNNRjdDM29qZmhmVVUKTjU5cXV4bmo0K2R5cktYaGhQVjJTRS9FNFJqemxMeG42QlRkRTIrUHRidjdQeDhPcnlRUGNXQ3RQamM3SmpWbAo3UmduVUhRbGRzOTJpK2NlTUc3dHZXSTNOdHZub3lpeE1lZlcvaThMMVFJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWV4K2NSSCsvR1kyajI4NnAKdGpCMDdTelpSN0F3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUsvSGd4UkxOVmw5Sis5NlZKYk5OYVRwNFY5bwpaZjAvcERpaGlYTXIyT0Z0RGlnOXc5VGVWV2M5b1lhOUVDWFVpM0hzbmtUS1grNExpTTNGdVZldHpXNHQwei9XCmJSZFU1ZGFIbHlDdi9OcnBuRmVQSUhiMmhybWtJN2djTFhpT1JhdUpHN3phM0RnTlZiUy9iZEd1M0lzd2k2ZFQKQTV4QTB6R0ZVamVPdFE5cHUvSERwUDJ0L0JyNjFJRVVEdGQrVGlVejZ0WUcybmV4ZHNKclRrNms1eXFxVHRNSwpHenppNlJtTjVSaEhCcUtqM0VhcDZQa1ZFNkhnY2NoWDRKTzF5b3VQTFBsRlZEZE1zRnE4amkyMkpuN2dLRHNzClhPWFFjMEprVXdGa0xQV3A3UnhyK0hKcXpQbkN4dGJjQ3BQQTFrRmw0V2krVTBDSWhRUFhCTmYyQjdrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 5
